spring:
  application:
    name: spring-ai
  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: qwen3:4b
    openai:
      api-key: ${api_key}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile



